### ISSUE TITLE
Digital Readout Development

### ISSUE THREAD

**Issue by RudraP-11285** [NIWC-Intern-Team/GUS-GUI-#12]
Data transferred from the ROS 2 network must be handled by the data manager before being transferred to the testing system. First, the connection between the data manager and the testing system will be developed and tested, then the connection between the ROS 2 network and the data manager will be worked on.

- [x] Read from CSV file  
- [x] Display data on readouts
- [x] #23 
- [x] #24 
- [x] #25 
- [x] #51

**Comment by gentleben8282** [comment]
Hannah requested that the fields that she designated to be on the default screen to be displayed on the All tab, and that the fields she designated to be on the secondary screen to be displayed on the diagnostics panel of the tabs for each individual vessel.

These designations were made via an email that Hannah sent to the development team.

**Comment by gentleben8282** [comment]
I completed the rearrangement of the diagnostic fields for the tabs of the individual vessels, so I am closing this issue again.
